CREATE DATABASE DATH_METADATA
GO
USE DATH_METADATA
GO 

CREATE TABLE [dbo].[Stage] (
  [ID] int IDENTITY(1, 1) NOT NULL,
  [TenBang] varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  [NgayCapNhat] datetime NULL
)
ON [PRIMARY]
GO

CREATE TABLE [dbo].[NDS] (
  [ID] int IDENTITY(1, 1) NOT NULL,
  [TenBang] varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  [NgayCapNhat] datetime NULL
)
ON [PRIMARY]
GO

CREATE TABLE [dbo].[DDS] (
  [ID] int IDENTITY(1, 1) NOT NULL,
  [TenBang] varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
  [NgayCapNhat] datetime NULL
)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[Stage]
ADD CONSTRAINT [PK_Stage] 
PRIMARY KEY CLUSTERED ([ID])
WITH (
  PAD_INDEX = OFF,
  IGNORE_DUP_KEY = OFF,
  STATISTICS_NORECOMPUTE = OFF,
  ALLOW_ROW_LOCKS = ON,
  ALLOW_PAGE_LOCKS = ON)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[NDS]
ADD CONSTRAINT [PK_NDS] 
PRIMARY KEY CLUSTERED ([ID])
WITH (
  PAD_INDEX = OFF,
  IGNORE_DUP_KEY = OFF,
  STATISTICS_NORECOMPUTE = OFF,
  ALLOW_ROW_LOCKS = ON,
  ALLOW_PAGE_LOCKS = ON)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[DDS]
ADD CONSTRAINT [PK_DDS] 
PRIMARY KEY CLUSTERED ([ID])
WITH (
  PAD_INDEX = OFF,
  IGNORE_DUP_KEY = OFF,
  STATISTICS_NORECOMPUTE = OFF,
  ALLOW_ROW_LOCKS = ON,
  ALLOW_PAGE_LOCKS = ON)
ON [PRIMARY]
GO